EasyShop/My-T-Shirt/My-T-Shirt/Controllers/PanierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using My_T_Shirt.Models;
using My_T_Shirt.ViewModel;
using My_T_Shirt.Helpers;

namespace My_T_Shirt.Controllers
{
    public class PanierController : Controller
    {
        // GET: Panier
        public ActionResult Index()
        {
            if (d.cn.State == System.Data.ConnectionState.Open)
                d.cn.Close();
            return View(GrProduit.GetPanier());
        }

        [HttpPost]
        public JsonResult AjouterAuPanier(ProduitPanier produit)
        {
            try
            {
                GrProduit.AjouterAuPanier(produit);
                return Json(new { done = true }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                Response.StatusCode = 500;
                return Json(new { done = false,ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult inPanier(string idProduit ,string idTaille)
        {
            try
            {
                bool inPanier = GrProduit.inPanier(idProduit,idTaille);
                if (inPanier)
                {
                    return Json(new
                    {
                        done = true,
                        existe = true
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new
                    {
                        done = true,
                        existe = false
                    }, JsonRequestBehavior.AllowGet);
                }
               
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                return Json(new { done = false, ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult AugmenterQte(string idProduit,string idTaille)
        {
            try
            {
                GrProduit.AugmenterQte(idProduit, idTaille);
                return Json(new { done = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;

                return Json(new { done = false, ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult DiminuerQte(string idProduit,string idTaille)
        {
            try
            {
                GrProduit.DiminuerQte(idProduit,idTaille);
                return Json(new { done = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;

                return Json(new { done = false, ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult supprimerDuPanier(string idProduit, string idTaille)
        {
            try
            {
                GrProduit.supprimerDuPanier(idProduit,idTaille);
                return Json(new { done = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;

                return Json(new { done = false, ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

EasyShop/My-T-Shirt/My-T-Shirt/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using My_T_Shirt.Models;
using PagedList;
namespace My_T_Shirt.Controllers
{
    public class ProduitsController : Controller
    {
        // GET: Produits
        public ActionResult Index(int? page, string recherche = "", string genre = "")
        {
            if (d.cn.State == System.Data.ConnectionState.Open)
                d.cn.Close();
            if (recherche != "")
            {
                ViewBag.recherche = recherche;
            }
            if (genre != "")
            {
                ViewBag.genre = genre;
            }
            const int pageSize = 16;
            int pageNumbre = page ?? 1;
            return View(Produit.Affcher(recherche, genre).ToPagedList(pageNumbre, pageSize));


        }

        [HttpGet]
        [ChildActionOnly]
        public ActionResult RenderSoldeProduits()
        {
            List<Produit> lstProduits = new List<Produit>();
            SqlCommand cmd = new SqlCommand("select top 10 p.* from produit p inner join solde s on p.idProduit = s.idProduit", d.cn);
            d.cn.Open();
            SqlDataReader dataR = cmd.ExecuteReader();
            while (dataR.Read())
            {
                Produit produit = new Produit();
                produit.IdProduit = dataR[0].ToString();
                produit.Nom = dataR[1].ToString();
                produit.Description = dataR[2].ToString();
                produit.Genre = dataR[3].ToString();
                produit.Prix = float.Parse(dataR[4].ToString());
                produit.Image = dataR[5].ToString();
                produit.idMarque = dataR[6].ToString();
                lstProduits.Add(produit);
            }
            dataR.Close();
            d.cn.Close();
            ViewData["soldeProduits"] = lstProduits;
            return PartialView("_SoldeProduits");
        }
       
    }
}

EasyShop/My-T-Shirt/My-T-Shirt/Views/Panier/Index.cshtml
@model List<My_T_Shirt.ViewModel.ProduitPanier>
@{
    ViewBag.Title = "Panier";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div>
        @if (Model.Count == 0)
        {
            <div class="jumbotron jumbotron-fluid mt-3">
                <div class="justify-content-center d-flex">
                    <h1>Your Cart is empty</h1>
                </div>
            </div>
        }
        else
        {
            <div class="table-responsive">
                <table class="table mt-5">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Name</th>
                            <th>price</th>
                            <th>chosen size</th>
                            <th>Quantity</th>
                            <th></th>
                            <th></th>

                            <th>Total</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="panier-tbody">
                        @foreach (var produit in Model)
                        {
                            <tr>
                                <td>
                                    <a href="/DetailsProduit?idProduit=@produit.idProduit">
                                        <img src="@produit.Image" alt="@produit.idProduit" class="img-thumbnail" style="width:70px" />
                                    </a>
                                </td>
                                <td>@produit.Nom</td>
                                <td><span>@produit.prix.ToString()</span> Rs</td>
                                <td>
                                    <div class="justify-content-center d-flex">
                                       @My_T_Shirt.Models.Taille.getNom(produit.idTaille)
                                    </div>
                                </td>
                                <td colspan="3">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="btn btn-primary btn-sm btn-diminuer-qte" data-id="@produit.idProduit" data-idTaille="@produit.idTaille"><i class="fas fa-minus"></i> </button>
                                        </div>
                                        <input type="text" class="form-control form-control-sm txt-qte" value="@produit.qte" disabled style="text-align:center;width:65px;" />
                                        <div class="input-group-append">
                                            <button class="btn btn-primary btn-sm btn-sm btn-augmenter-qte" data-id="@produit.idProduit" data-idTaille="@produit.idTaille" data-qte-stock="@My_T_Shirt.Models.Produit.getTailleQteStock(produit.idProduit,produit.idTaille)"><i class="fas fa-plus"></i></button>
                                        </div>
                                    </div>
                                </td>
                                <td class="total"><span>@(produit.qte * produit.prix)</span> Rs</td>
                                <td>
                                    <button class="btn btn-danger btn-sm btn-supprimer" data-id="@produit.idProduit" data-idTaille="@produit.idTaille"><i class="fas fa-trash-alt"></i></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }</div>
        <hr />
        <div class="justify-content-end d-flex mb-5">
            <ul class="list-group" style="width:400px">
                <li class="list-group-item">
                    <div class="justify-content-between d-flex">
                        <label>Number of products :</label>
                        <label id="lbl-nbr-prod"><span>@Model.Count</span></label>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="justify-content-between d-flex">
                        <label>Total Amount : </label>
                        <label id="lbl-mt"><span>0</span> Rs</label>
                    </div>
                </li>
                <li class="list-group-item">
                    <button class="btn btn-primary btn-block" id="btn-acheter">
                        Buy
                    </button>
                </li>
            </ul>
        </div>
        <hr />
        <!--Solde-->
        <div class="mb-5">
            <div class="justify-content-center d-flex mt-5 mb-5">
                <h2 class="m-title">Products on sale</h2>
            </div>
            <div>
                @{
                    Html.RenderAction("RenderSoldeProduits", "Produits");
                }
            </div>
        </div>
        <!--Solde-->
    </div>
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
          
            
            function getMtTotal() {
                var mt = 0;
                $(".total").each(function (i, item) {
                    var t = item.querySelector("span").innerText.split(",")[0] + "."+item.querySelector("span").innerText.split(",")[1];
                    mt += parseFloat(t);
                });
                
                $("#lbl-mt").find("span").html(mt.toString().substring(0,7));
            }

            function getNbrProd() {
                var nbrProd = 0;
                $(".txt-qte").each(function (i, item) {
                    nbrProd += parseInt(item.value);
                });
                $("#lbl-nbr-prod").html(nbrProd);
            }
           
            $(".btn-diminuer-qte").on("click", function () {
                var txtqte = $(this).parent().parent().find("input");
                var idProduit = $(this).data().id;
                var idTaille = $(this).attr("data-idTaille");

                var btn = $(this);
                var qte = 0
                if (txtqte.val() != 1) {
                    
                    $.ajax({
                        method: 'POST',
                        url: "@Url.Action("DiminuerQte", "Panier")",
                        data: JSON.stringify({ idProduit, idTaille }),
                        contentType: "application/json",
                        success: function (resp) {
                            console.log(resp);
                            qte = parseInt(txtqte.val()) - 1
                            txtqte.val(qte);
                            var prix = btn.parent().parent().parent().parent().find("td").eq(2).find('span').text();
                            var el_total = btn.parent().parent().parent().parent().find("td").eq(5).find('span');
                            var t_prix = prix.split(",")[0] + "." + prix.split(",")[1]
                            var total = parseFloat(parseFloat(t_prix) * qte);

                            el_total.text(total.toString().substring(0, 7));

                            getMtTotal();

                            getNbrProd();
                        }, error: function (resp) {
                            console.log(resp);
                        }
                    });
                }

            });

            $(".btn-augmenter-qte").on("click", function () {
                var btn = $(this);
                var qteStock = $(this).data().qteStock;
                var idProduit = $(this).data().id;
                var idTaille = $(this).attr("data-idTaille");
                var txtqte = $(this).parent().parent().find("input");
                var qte = 0
                if (txtqte.val() != qteStock) {

                    $.ajax({
                        method: 'POST',
                        url: "@Url.Action("AugmenterQte", "Panier")",
                        data: JSON.stringify({ idProduit, idTaille }),
                        contentType:"application/json",
                        success: function (resp) {
                            console.log(resp);
                            qte = parseInt(txtqte.val()) + 1
                            txtqte.val(qte);

                            var prix = btn.parent().parent().parent().parent().find("td").eq(2).find('span').text();
                            var el_total = btn.parent().parent().parent().parent().find("td").eq(5).find('span');
                            var t_prix = prix.split(",")[0] + "." + prix.split(",")[1];
                            var total = parseFloat(parseFloat(t_prix) * qte);



                            el_total.text(total.toString().substring(0, 7));

                            getMtTotal();
                            getNbrProd();
                        },
                        error: function (resp) {
                            console.log(resp);
                        }
                    });

                }
            });


            $(".btn-supprimer").on("click", function () {
                var idProduit = $(this).data().id;
                var idTaille = $(this).attr("data-idTaille");

       
                var ligne = $(this).parent().parent();
                var tbody = ligne.parent();
                var table = tbody.parent();
                var parentDiv = table.parent().parent();
                $.ajax({
                    method: 'POST',
                    url: "@Url.Action("supprimerDuPanier", "Panier")",
                    data: JSON.stringify({ idProduit, idTaille}),
                    contentType: "application/json",
                    success: function (resp) {
                        console.log(resp);
                        ligne.remove();
                        if (tbody.children().length == 0) {
                            table.remove();
                            const msg = `<div class="jumbotron jumbotron-fluid mt-3">
                                            <div class="justify-content-center d-flex">
                                                <h1>Your Cart is Empty</h1>
                                            </div>
                                        </div>`;
                            parentDiv.html(msg)
                        }
                        getMtTotal();
                        getNbrProd();
                    },
                    error: function (resp) {
                        console.log(resp);
                    },
                })
            });

            $("#btn-acheter").on("click", function () {
                var isValid = true;
                if ($("#panier-tbody").length == 0) {
                    isValid = false;
                    Swal.fire({
                        title: 'Alert',
                        text: "Your Cart is Empty",
                        icon: "info",
                        confirmButtonColor: 'var(--primary)',
                    });
                }
                if (!isConnected() && $("#panier-tbody").length != 0) {
                    isValid = false;
                    Swal.fire({
                        title: 'Alert',
                        text: "Login First",
                        icon: "info",
                        confirmButtonColor: 'var(--primary)',
                    });
                }

                if (isValid) {
                    window.location.href = "/AdresseCommande";
                } 

            });
            getMtTotal();
            getNbrProd();
        });
    </script>
}