EasyShop/My-T-Shirt/My-T-Shirt/Controllers/MonCompteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using My_T_Shirt.Helpers;
using My_T_Shirt.Models;
using My_T_Shirt.ViewModel;
using System.Data.SqlClient;

namespace My_T_Shirt.Controllers
{
    public class MonCompteController : Controller
    {
        // GET: MonCompte
        public ActionResult Index()
        {
            if(Authentication.isConnected())
            {
                if (d.cn.State == System.Data.ConnectionState.Open)
                    d.cn.Close();

                List<Commande> lstcommandes = new List<Commande>();
                string req1 = string.Format("select * from commande where idUtilisateur = '{0}' order by Date_Com desc ", Authentication.getId(false));
                SqlCommand cmd1 = new SqlCommand(req1, d.cn);
                d.cn.Open();
                SqlDataReader dataR1 = cmd1.ExecuteReader();
                while (dataR1.Read())
                {
                    Commande commande = new Commande();
                    commande.IdCommande = dataR1[0].ToString();
                    commande.idUtilisateur = dataR1[1].ToString();
                    commande.Adresse_Com = dataR1[2].ToString();
                    commande.Ville_Com = dataR1[3].ToString();
                    commande.CodePostal_Com = dataR1[4].ToString();
                    commande.Pays_Com = dataR1[5].ToString();
                    commande.Date_Com = DateTime.Parse(dataR1[6].ToString());
                    commande.isDelivered = bool.Parse(dataR1[7].ToString());

                    if (dataR1[8].ToString() != "")
                    {
                        commande.Date_Livraison = DateTime.Parse(dataR1[8].ToString());
                    }
                    lstcommandes.Add(commande);
                }
                dataR1.Close();
                d.cn.Close();
                return View(lstcommandes);
            }
            else
            {
                return RedirectToAction("", "SeConnecter");
            }
        }

        public ActionResult SeDeconnecter()
        {
            Authentication.seDeconnecter(false);
            GrProduit.SupprimerPanier();
            GrProduit.SupprimerAdresseCommande();
            return RedirectToAction("","Accueil");
        }

        [HttpPost]
        public JsonResult ModifierInfo(ChangerNomPrenom model)
        {
            try
            {
                if (model != null)
                {
                    string req = string.Format(@"update utilisateur set nom = '{0}', prenom = '{1}' 
                                                where idUtilisateur='{2}' ",
                                                model.nom, model.prenom, Authentication.getId(false));

                    SqlCommand cmd = new SqlCommand(req, d.cn);
                    d.cn.Open();
                    cmd.ExecuteNonQuery();
                    d.cn.Close();
                    if (Request.Cookies["Login"] != null)
                    {
                        HttpCookie cookie = Request.Cookies["Login"];
                        cookie.Values["Nom"] = model.nom;
                        cookie.Values["Prenom"] = model.prenom;
                        cookie.Expires = DateTime.Now.AddDays(1);
                        Response.SetCookie(cookie);
                    }
                    return Json(new { done = true });
                }
                else
                {
                    Response.StatusCode = 500;
                    return Json(new { done = false, Message = "Model null !!" });
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                return Json(new { done = false, ex.Message });
            }
        }

        [HttpPost]
        public JsonResult ModfierMotDePasse(ChangerMotDePasse model)
        {
            try
            {
                bool existe = false;
                string motdepasse = "";
                string req1 = string.Format(@"select motdepasse from Utilisateur
                                              where idUtilisateur = '{0}' ",
                                              Authentication.getId(false));

                SqlCommand cmd1 = new SqlCommand(req1, d.cn);
                d.cn.Open();
                if (cmd1.ExecuteScalar() != null)
                {
                    motdepasse = Cryptage.Decrypt(cmd1.ExecuteScalar().ToString());
                    if (motdepasse == model.MotDePasseActuel)
                        existe = true;

                }
                d.cn.Close();
                if (existe)
                {
                    string req2 = string.Format("update Utilisateur set motdepasse='{0}' where idUtilisateur='{1}'",Cryptage.Encrypt(model.NouveauMotDePasse), Authentication.getId(false));
                    SqlCommand cmd2 = new SqlCommand(req2, d.cn);
                    d.cn.Open();
                    cmd2.ExecuteNonQuery();
                    d.cn.Close();

                    return Json(new
                    {
                        done = true,
                    });

                }
                else
                {
                    Response.StatusCode = 404;
                    return Json(new
                    {
                        done = false,
                        Message = "Mot de passe actuel incorrect !"
                    });
                }

            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                return Json(new
                {
                    done = false,
                    ex.Message,
                    model
                });
            }
        }
    }
}

EasyShop/My-T-Shirt/My-T-Shirt/Views/MonCompte/Index.cshtml
@model List<My_T_Shirt.Models.Commande>
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    label.error {
        color: var(--danger);
        margin-top: 3px;
    }
</style>

<div class="container mt-5">
    <h4>user : <span class="text-success">@My_T_Shirt.Helpers.Authentication.getEmail(false)</span></h4>
    <hr />
    <nav class="mt-5">
        <div class="nav nav-tabs">
            <a class="nav-link active" id="nav-mes-commandes-tab" data-toggle="tab" href="#mes-commandes" aria-controls="true">My orders</a>
            <a class="nav-link" id="nav-modfier-nom-prenom-tab" data-toggle="tab" href="#modifier-nom-prenom" aria-controls="false">Change surname / first name</a>
            <a class="nav-link" id="nav-modfier-mot-de-passe" data-toggle="tab" href="#modifier-mot-de-passe" aria-controls="false">Change password</a>
        </div>
    </nav>
    <div class="tab-content">

        <div class="tab-pane fade show active" id="mes-commandes" role="tabpanel" aria-labelledby="nav-mes-commandes-tab">
            @if (Model.Count == 0)
            {
                <div class="jumbotron mt-5">
                    <div class="justify-content-center d-flex">
                        <h4>please place orders</h4>
                    </div>
                </div>
            }
            else
            {
                <div class="table-responsive mt-5">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>Order ID</th>
                                <th>Order date</th>
                                <th>Total Amount</th>
                                <th>Delivered</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var commande in Model)
                            {
                                <tr>
                                    <th>@commande.IdCommande</th>
                                    <th>@commande.Date_Com</th>
                                    <th>@My_T_Shirt.Models.Commande.getMontantTotal(commande.IdCommande) Rs</th>
                                    <th>
                                        @if (commande.isDelivered)
                                        {
                                            <span class="text-success">@DateTime.Parse(commande.Date_Livraison.ToString()).ToShortDateString()&nbsp;@DateTime.Parse(commande.Date_Livraison.ToString()).ToLongTimeString()</span>
                                        }
                                        else
                                        {
                                            <span class="text-danger justify-content-center d-flex"><i class="fas fa-times"></i></span>
                                        }
                                    </th>
                                    <th>
                                        <a href="/Commande?idCommande=@commande.IdCommande" class="btn btn-secondary btn-sm">
                                            details
                                        </a>
                                    </th>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>

        <div class="tab-pane fade" id="modifier-nom-prenom" role="tabpanel" aria-labelledby="nav-modfier-nom-prenom-tab">
            <div class="mt-5" style="padding:0 20% 0 20%">
                <form id="frmModNomPrenom">
                    <div class="form-group">
                        <label>First Name</label>
                        <input type="text" class="form-control" value="@My_T_Shirt.Helpers.Authentication.getNom(false)" name="txt-nom" id="txt-nom" />
                    </div>
                    <div class="form-group">
                        <label>Last Name</label>
                        <input type="text" class="form-control" value="@My_T_Shirt.Helpers.Authentication.getPrenom(false)" name="txt-prenom" id="txt-prenom" />
                    </div>
                   
                    <button class="btn btn-primary btn-block" type="submit">Modifier</button>
                </form>
            </div>
        </div>

        <div class="tab-pane fade" id="modifier-mot-de-passe" role="tabpanel" aria-labelledby="nav-modfier-mot-de-passe">
            <div class="mt-5" style="padding:0 20% 0 20%">
                <form id="frmModMdp">
                    <div class="form-group">
                        <label>Current Password </label>
                        <input type="password" class="form-control" name="txt-mdp-actuel" id="txt-mdp-actuel" />
                    </div>
                    <div class="form-group">
                        <label>New Password</label>
                        <input type="password" class="form-control" name="txt-new-mdp" id="txt-new-mdp" />
                    </div>
                    <div class="form-group">
                        <label>Confirm the new password</label>
                        <input type="password" class="form-control" name="txt-confirm-new-mdp" id="txt-confirm-new-mdp" />
                    </div>
                    <button class="btn btn-primary btn-block">Modify</button>
                  </form>
            </div>
        </div>
        </div>
 </div>
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function(){
            $("#frmModNomPrenom").validate({
                rules: {
                    "txt-nom": {
                        required: true,
                    },
                    "txt-prenom": {
                        required: true,
                    }
   
                },
                messages: {
                    "txt-nom": {
                        required: "you have to enter the First name",
                    },
                    "txt-prenom": {
                        required: "you have to enter the Last name",
                    },
                },
                submitHandler: function () {

                    const objToSend = {
                        nom: $("#txt-nom").val(),
                        prenom: $("#txt-prenom").val(),
                    };
                    
                    $.ajax({
                        method: "post",
                        url: "@Url.Action("ModifierInfo", "MonCompte")",
                        data: JSON.stringify(objToSend),
                        contentType:"application/json",
                        success: function (resp) {
                            console.log(resp);
                            $("#navbar-nom").text(objToSend.nom);
                            $("#navbar-prenom").text(objToSend.prenom);

                            Swal.fire({
                                title: 'Alert',
                                text: "Change made with success",
                                icon: "success",
                                confirmButtonColor: 'var(--success)',
                            });
                        },
                        error: function (resp) {
                            console.log(resp);
                        }
                    });


                }
            });

             $("#frmModMdp").validate({
                rules: {
                    "txt-mdp-actuel": {
                        required:true,
                    },
                    "txt-new-mdp": {
                        required: true,
                        minlength:5,
                    },
                    "txt-confirm-new-mdp": {
  
                        equalTo: "#txt-new-mdp"
                    },
                 },
                 messages: {
                     "txt-mdp-actuel": {
                         required: "you must enter the current password",
                     },
                     "txt-new-mdp": {
                         required: "you have to enter the new password",
                         minlength: "weak password!",
                     },
                     "txt-confirm-new-mdp": {
                         equalTo: "The password and the confirmation password must be identical!"
                     },
                 },
                submitHandler: function () {
                    const objToSend = {
                        MotDePasseActuel: $("#txt-mdp-actuel").val(),
                        NouveauMotDePasse: $("#txt-new-mdp").val(),
                    };

                    $.ajax({
                        method: "post",
                        url: "@Url.Action("ModfierMotDePasse", "MonCompte")",
                        data: JSON.stringify(objToSend),
                        contentType: "application/json",
                        success: function (resp) {
                            console.log(resp);

                            Swal.fire({
                                title: 'Alert',
                                text: "Change made successfully",
                                icon: "success",
                                confirmButtonColor: 'var(--success)',
                            });

                            $("#txt-mdp-actuel").val("");
                            $("#txt-new-mdp").val("");
                            $("#txt-confirm-new-mdp").val("");

                        },
                        error: function (resp) {
                         console.log(resp);
                            Swal.fire({
                                title: 'Alert',
                                text: resp.responseJSON.Message,
                                icon: "error",
                                confirmButtonColor: 'var(--danger)',
                            });
                        }
                    })
                }
            });
        });
    </script>
}