EasyShop/My-T-Shirt/My-T-Shirt/Controllers/AdresseCommandeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using My_T_Shirt.Models;
using My_T_Shirt.Helpers;
using My_T_Shirt.ViewModel;

namespace My_T_Shirt.Controllers
{
    public class AdresseCommandeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            if (Authentication.isConnected())
            {
                if (GrProduit.GetPanier().Count != 0)
                {
                    if (d.cn.State == System.Data.ConnectionState.Open)
                        d.cn.Close();

                    ViewBag.error = "";
                    return View(GrProduit.GetAdresseCommande());
                }
                else
                {
                    return RedirectToAction("", "Panier");
                }
            }
            else
            {
                return RedirectToAction("", "SeConnecter");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(AdresseCommande adresse)
        {
            try
            {
                ViewBag.error = "";
                if (adresse != null)
                {

                    GrProduit.setAdresseCommande(adresse);
                    return RedirectToAction("", "ValiderCommande");
                }
                else
                {
                    ViewBag.error = "Erreur adresse null !";
                    return View();
                }
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View();
            }
        }

        [HttpPost]
        public ActionResult setAdresseCommande(AdresseCommande adresse)
        {
            try
            {
                ViewBag.error = "";
                if (adresse != null)
                {

                    GrProduit.setAdresseCommande(adresse);
                    return Json(new { done = true, adresse },JsonRequestBehavior.AllowGet);
                }
                else
                {
                    Response.StatusCode = 404;

                    return Json(new { done = false,Message="adresse introuvable !" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                ViewBag.error = ex.Message;
                return Json(new { done = false ,ex.Message}, JsonRequestBehavior.AllowGet);

            }
        }
    }
}

EasyShop/My-T-Shirt/My-T-Shirt/Views/AdresseCommande/Index.cshtml
@model My_T_Shirt.ViewModel.AdresseCommande
@*@model My_T_Shirt.Models.Solde*@
@{
    ViewBag.Title = "Adresse commande";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    label.error {
        color: var(--danger);
        margin-top: 3px;
    }

    .track-line {
        height: 2px !important;
        background-color: var(--primary);
    }

        .track-line.nn-track-line {
            background-color: #f4f4f4;
        }

    .dot {
        height: 35px;
        width: 35px;
        margin-left: 0px;
        margin-right: 0px;
        margin-top: 0px;
        background-color: var(--primary);
        border-radius: 50%;
        display: inline-block;
        position: relative
    }

    .-dot i {
        font-size: 12px
    }

    .dot small {
        position: absolute;
        color: gray;
        margin-top: 10px;
        top: 100%;
        width: 100%;
    }

    .dot.nn-dot {
        background-color: #f4f4f4;
    }
</style>


<div class="container mt-5">


    <div class="row mb-5">
        <div class="col-md-12 mb-5">

            <div class="d-flex flex-row justify-content-between align-items-center align-content-center">
                <span class="dot d-flex justify-content-center align-items-center">
                    <i class="fa fa-check text-white"></i>
                    <small>Login</small>
                </span>

                <hr class="flex-fill track-line">

                <span class="dot d-flex justify-content-center align-items-center nn-dot">
                    <small>order address</small>
</span>

                <hr class="flex-fill track-line nn-track-line">
                <span class="dot d-flex justify-content-center align-items-center nn-dot">
                    <small>Validate the order</small>
                </span>
            </div>
        </div>
    </div>
    <hr class="mt-5 mb-5" />

    <div class="row">
        <div class="col-xl-8 col-lg-8  col-md-8 col-sm-12">
            <div class="justify-content-center d-flex mt-2">
                <h4 class="m-title">Enter the order address</h4>
            </div>
            @if (ViewBag.error != "")
            {
                <div class="alert alert-danger">
                    <div class="justify-content-center d-flex">
                        <h4>@ViewBag.error</h4>
                    </div>
                </div>
            }

            @using (Html.BeginForm("", "", FormMethod.Post, new { id = "frm-adresse" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label for="txt-pays">Country</label>
                @Html.TextBoxFor(m => m.pays, new { @autocomplete = "off", @class = "form-control",id="txt-pays" })
            </div>
            <div class="form-group">
                <label for="txt-ville">City</label>
                @Html.TextBoxFor(m => m.ville, new { @autocomplete = "off", @class = "form-control", id = "txt-ville" })
            </div>
            <div class="form-group">
                <label for="txt-code-postal">Postal Code</label>
                @Html.TextBoxFor(m => m.codePostal, new { @autocomplete = "off", @class = "form-control", id = "txt-codePostal" })

            </div>
            <div class="form-group">
                <label for="txt-adresse">Address</label>
                @Html.TextAreaFor(m => m.adresse, new { @autocomplete = "off", @class = "form-control", id = "txt-adresse" })
            </div>
                @*<div class="form-group">
                    @Html.TextBoxFor(m => m.IdProduit, new { @autocomplete = "off", @class = "form-control" })
                </div>*@

        <button class="btn btn-block btn-primary" type="submit">validate the address</button>
            }
        </div>

        <div class="col-xl-4 col-lg-4  col-md-4 col-sm-12 mt-2">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="justify-content-between d-flex">
                        <label>Number of product:</label>
                        <label id="lbl-nbr-prod"> 0</label>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="justify-content-between d-flex">
                        <label>Total amount :</label>
                        <label id="lbl-mt"><span>0</span>Rs</label>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="alert alert-info p-2 mb-0">
                        <div class="justify-content-center d-flex">
                            <h5 class="mt-2">Free delivery</h5>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function(){
            const panier = JSON.parse(getCookie("Panier"));;
            let nbr = 0;
            let mt = 0;

            $.each(panier, function (i, produit) {
                nbr += produit.qte;
                let t_prix = produit.prix;
                mt += parseFloat(t_prix * produit.qte);
            });

            $("#lbl-nbr-prod").text(nbr);
            $("#lbl-mt").find("span").text(mt);

            $("#frm-adresse").validate({
                rules: {
                    "ville": {
                        required: true,
                    },
                    "pays": {
                        required: true,
                    },
                    "codePostal": {
                        required: true,
                        maxlength: 5,
                        minlength: 5,
                        number: true,
                    },
                    "adresse": {
                        required: true,
                    }
                },
                messages: {
                    "ville": {
                        required: "you have to enter the city",
                    },
                    "pays": {
                        required: "you have to enter the country"
                    },
                    "codePostal": {
                        required: "you must enter the postal code",
                    },
                    "adresse": {
                        required: "you have to enter the address",
                    }
                },
                submitHandler: function () {
                    const adresse = {
                        pays: $("#txt-pays").val(),
                        ville: $("#txt-ville").val(),
                        codePostal: $("#txt-codePostal").val(),
                        adresse: $("#txt-adresse").val(),

                    };

                    @*$.ajax({
                        method: "post",
                        url: "@Url.Action("setAdresseCommande", "AdresseCommande")",
                        data: JSON.stringify(adresse),
                        contentType:'application/json',
                        success: function (resp) {
                            console.log(resp);
                        },
                        error: function (resp) {
                            console.log(resp);
                            Swal.fire(
                                'Alert',
                                "Erreur du serveur",
                                'info'
                            );
                        }
                    })*@

                    setCookie("AdresseCommande", JSON.stringify(adresse), 0.1);
                    window.location.href = "/ValiderCommande";
                },

            });
        });
    </script>
}